global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: false
  width: 20.0
  height: 20.0
  resolution: 0.05
  transform_tolerance: 0.5
  map_type: costmap
  inflation_layer:
    inflation_radius: 0.55
