controller_frequency: 10.0
max_trans_vel: 0.5
min_trans_vel: 0.1
max_vel_x: 0.5
min_vel_x: 0.1
max_vel_y: 0.0
min_vel_y: 0.0
max_rotational_vel: 1.0
min_in_place_rotational_vel: 0.6
acc_lim_x: 1.0
acc_lim_theta: 2.0
yaw_goal_tolerance: 0.1
xy_goal_tolerance: 0.1
